#!/bin/bash
set -euo pipefail

# Only run in remote (Codespaces / Claude Code on the web) environments
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-$(pwd)}"

# ── Write .env.local from Codespaces secrets ──────────────────────────────────
ENV_FILE=".env.local"

{
  echo "# Auto-generated by session-start.sh — do not edit manually"
  echo ""

  for var in \
    NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY \
    SUPABASE_SERVICE_ROLE_KEY \
    ANTHROPIC_API_KEY \
    NEXT_PUBLIC_APP_URL \
    SUPABASE_ACCESS_TOKEN \
    SUPABASE_PROJECT_REF \
    SUPABASE_DB_PASSWORD; do
    val="${!var:-}"
    if [ -n "$val" ]; then
      echo "${var}=${val}"
    else
      echo "# WARNING: ${var} is not set — add it as a Codespaces secret"
    fi
  done
} > "$ENV_FILE"

echo "✓ Wrote $ENV_FILE"

# ── Install dependencies ──────────────────────────────────────────────────────
if [ -f "package-lock.json" ]; then
  echo "Installing npm dependencies..."
  npm install
  echo "✓ npm install complete"
fi

# ── Run pending database migrations ──────────────────────────────────────────
if [ -n "${SUPABASE_ACCESS_TOKEN:-}" ] && [ -n "${SUPABASE_PROJECT_REF:-}" ] && [ -n "${SUPABASE_DB_PASSWORD:-}" ]; then
  echo "Linking Supabase project..."
  npx supabase link \
    --project-ref "$SUPABASE_PROJECT_REF" \
    --password "$SUPABASE_DB_PASSWORD" 2>&1 || true

  echo "Applying pending migrations..."
  npx supabase db push \
    --password "$SUPABASE_DB_PASSWORD" 2>&1 \
    && echo "✓ Migrations up to date" \
    || echo "⚠ Migration step failed — check Supabase dashboard"
else
  echo "# Skipping migrations — SUPABASE_ACCESS_TOKEN / SUPABASE_PROJECT_REF / SUPABASE_DB_PASSWORD not set"
fi

# ── Propagate env vars to the Claude session ─────────────────────────────────
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  for var in \
    NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY \
    SUPABASE_SERVICE_ROLE_KEY \
    ANTHROPIC_API_KEY \
    NEXT_PUBLIC_APP_URL \
    SUPABASE_ACCESS_TOKEN \
    SUPABASE_PROJECT_REF \
    SUPABASE_DB_PASSWORD; do
    val="${!var:-}"
    if [ -n "$val" ]; then
      echo "export ${var}=\"${val}\"" >> "$CLAUDE_ENV_FILE"
    fi
  done
  echo "✓ Exported vars to Claude session"
fi
