#!/bin/bash
set -euo pipefail

# Only run in remote (Codespaces / Claude Code on the web) environments
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-$(pwd)}"

# ── Write .env.local from Codespaces secrets ──────────────────────────────────
# Codespaces injects secrets as environment variables.
# We write them to .env.local so Next.js picks them up at build/dev time.
ENV_FILE=".env.local"

{
  echo "# Auto-generated by session-start.sh — do not edit manually"
  echo ""

  # Required — these must be set as Codespaces secrets
  for var in \
    NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY \
    SUPABASE_SERVICE_ROLE_KEY \
    ANTHROPIC_API_KEY \
    NEXT_PUBLIC_APP_URL; do
    val="${!var:-}"
    if [ -n "$val" ]; then
      echo "${var}=${val}"
    else
      echo "# WARNING: ${var} is not set — add it as a Codespaces secret"
    fi
  done
} > "$ENV_FILE"

echo "✓ Wrote $ENV_FILE"

# ── Install dependencies ──────────────────────────────────────────────────────
if [ -f "package-lock.json" ]; then
  echo "Installing npm dependencies..."
  npm install
  echo "✓ npm install complete"
fi

# ── Propagate env vars to the Claude session ─────────────────────────────────
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  for var in \
    NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY \
    SUPABASE_SERVICE_ROLE_KEY \
    ANTHROPIC_API_KEY \
    NEXT_PUBLIC_APP_URL; do
    val="${!var:-}"
    if [ -n "$val" ]; then
      echo "export ${var}=\"${val}\"" >> "$CLAUDE_ENV_FILE"
    fi
  done
  echo "✓ Exported vars to Claude session"
fi
